using System.ComponentModel.DataAnnotations;

namespace AykutOnPC.Core.Entities;

/// <summary>
/// One turn of a chat conversation, persisted for telemetry, debugging,
/// short-term conversation memory, and admin review.
/// Streaming and non-streaming endpoints both write here.
/// </summary>
public class ChatLog
{
    public long Id { get; set; }

    /// <summary>Groups turns belonging to the same conversation. Generated by the server when missing.</summary>
    public Guid ConversationId { get; set; }

    /// <summary>0-based index of this turn within its conversation.</summary>
    public int TurnIndex { get; set; }

    [Required, MaxLength(2000)]
    public string UserMessage { get; set; } = string.Empty;

    [MaxLength(8000)]
    public string? BotResponse { get; set; }

    /// <summary>One of <see cref="ChatErrorKind"/>, stored as string for forward compatibility.</summary>
    [Required, MaxLength(20)]
    public string Kind { get; set; } = "Ok";

    /// <summary>Wall-clock latency of the model call in milliseconds.</summary>
    public int LatencyMs { get; set; }

    [MaxLength(100)]
    public string? ModelId { get; set; }

    /// <summary>True when the request was short-circuited by pre-flight rules and the model was never called.</summary>
    public bool ShortCircuited { get; set; }

    /// <summary>SHA-256 hash of the caller IP — same scheme used by <see cref="PageView"/>.</summary>
    [MaxLength(64)]
    public string HashedIp { get; set; } = string.Empty;

    [MaxLength(512)]
    public string? UserAgent { get; set; }

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Admin marked this turn as reviewed. Inbox sorting uses this to surface
    /// unreviewed turns at the top.
    /// </summary>
    public bool IsReviewed { get; set; }

    /// <summary>Free-form admin note ("KB'ye eklendi", "anlamsız soru", vb.).</summary>
    [MaxLength(1000)]
    public string? AdminNote { get; set; }

    /// <summary>
    /// FK to <see cref="KnowledgeEntry"/> when the turn was answered by promoting
    /// the bot reply (or admin's edit) into the KB. Null otherwise. Drives the
    /// closed feedback loop: visitor question → KB entry → next RAG retrieval.
    /// </summary>
    public int? LinkedKnowledgeEntryId { get; set; }
}

/// <summary>
/// Outcome class for a single chat turn. Drives error mapping to user messages
/// and frontend behavior (chip rendering, status dot color, etc.).
/// Stored as the string name in <see cref="ChatLog.Kind"/>.
/// </summary>
public enum ChatErrorKind
{
    /// <summary>Successful response delivered.</summary>
    Ok,
    /// <summary>Model returned no content (gibberish input, ambiguous prompt). Not an error — needs guidance UX.</summary>
    Empty,
    /// <summary>Provider safety filter / content policy block.</summary>
    Safety,
    /// <summary>Provider returned 429 / quota exhausted.</summary>
    RateLimit,
    /// <summary>Network / transport failure between server and provider.</summary>
    Network,
    /// <summary>Server-side input validation rejection (length, format).</summary>
    Validation,
    /// <summary>Provider unconfigured (missing API key).</summary>
    NotConfigured,
    /// <summary>Anything not classified above. Treated as a real backend error.</summary>
    Unknown
}
